# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clock
  pod 'RxSwift', '5.1.0'
  pod 'RxCocoa', '5.1.0'

end
